name: Build and push image from PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and push image from PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the image
        run: make build

      - name: Push PR image to the registry
        run: make pr-image
        env:
          TAG: ${{ github.head_ref }}
