name: Test

on:
  push:
    branches:
      - 11-ghcr-move

jobs:
  build:
    name: Test Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Build the image
        run: make build

      - name: Log in to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the image
        run: make publish
        env:
          TAG: test
