name: Test

on:
  push:
    branches:
      - 11-ghcr-move

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Build the image
        run: make build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish the image
        run: make publish
        env:
          TAG: test
